# ReferÃªncia:
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
---
name: Nova ConfiguraÃ§Ã£o RepositÃ³rio/Projeto âš™ï¸
projects: "nada-supera-a-persistencia/1"
description: Adicione uma nova tarefa de configuraÃ§Ã£o do projeto/repositÃ³rio
title: "[Conf]: Digite o tÃ­tulo da tarefa aqui"
labels: ["Nova configuraÃ§Ã£o"]

body:
  - type: textarea
    attributes:
      label: DescriÃ§Ã£o tarefa
      value: |
        **ğŸ¯ Objetivo:**
        Descreva o objetivo da tarefa aqui.

        **ğŸ“‹ Etapas:**
        1. [ ] Etapa 1 da tarefa
        2. [ ] Etapa 2 da tarefa

        **ResponsÃ¡vel:** @NomeDoResponsavel
        **Revisor:** @NomeDoRevisor
    validations:
      required: false